# ♥♥─── HabiTui Base Model Initialization ──────────────────────────────────────
"""Initializes the base models package."""

from __future__ import annotations

from .base_enums import (
    Attribute,
    ChallengeTaskKeepOption,
    DailyStatus,
    Frequency,
    HabitStatus,
    Priority,
    RewardStatus,
    ScoreDirection,
    TagsCategory,
    TagsTrait,
    TaskKeepOption,
    TaskStatus,
    TaskType,
    TodoStatus,
)
from .base_model import ContentMetadata, HabiTuiBaseModel, HabiTuiSQLModel
from .challenge_model import (
    ChallengeCollection,
    ChallengeInfo,
    ChallengeTaskDaily,
    ChallengeTaskHabit,
    ChallengeTaskReward,
    ChallengeTaskTodo,
)
from .content_model import ContentCollection, GearItem, QuestItem, SpellItem
from .creation_model import (
    ChallengeCreate,
    ChecklistItemCreate,
    DailyCreate,
    DailyRepeatPattern,
    HabitCreate,
    ReminderCreate,
    RewardCreate,
    TaskBaseCreate,
    TaskCreatePayload,
    TodoCreate,
)
from .message_model import PartyMessage, UserMessage
from .party_model import PartyCollection, PartyInfo
from .tag_model import TagCollection, TagComplex
from .task_model import (
    AnyTask,
    ChallengeInTask,
    TaskChecklist,
    TaskCollection,
    TaskDaily,
    TaskHabit,
    TaskReward,
    TaskStatusType,
    TaskTodo,
)
from .user_model import (
    ChallengeInUser,
    UserAchievements,
    UserCollection,
    UserCurrentState,
    UserHistory,
    UserNotifications,
    UserPreferences,
    UserProfile,
    UserStatsComputed,
    UserStatsRaw,
    UserTasksOrder,
    UserTimestamps,
)

__all__ = [
    "AnyTask",
    "Attribute",
    "Attribute",
    "ChallengeCollection",
    "ChallengeCreate",
    "ChallengeInTask",
    "ChallengeInUser",
    "ChallengeInfo",
    "ChallengeTaskDaily",
    "ChallengeTaskHabit",
    "ChallengeTaskKeepOption",
    "ChallengeTaskKeepOption",
    "ChallengeTaskReward",
    "ChallengeTaskTodo",
    "ChecklistItemCreate",
    "ContentCollection",
    "ContentMetadata",
    "ContentMetadata",
    "DailyCreate",
    "DailyRepeatPattern",
    "DailyStatus",
    "DailyStatus",
    "Frequency",
    "Frequency",
    "GearItem",
    "HabiTuiBaseModel",
    "HabiTuiBaseModel",
    "HabiTuiSQLModel",
    "HabiTuiSQLModel",
    "HabitCreate",
    "HabitStatus",
    "HabitStatus",
    "PartyCollection",
    "PartyInfo",
    "PartyMessage",
    "Priority",
    "Priority",
    "QuestItem",
    "ReminderCreate",
    "RewardCreate",
    "RewardStatus",
    "RewardStatus",
    "ScoreDirection",
    "ScoreDirection",
    "SpellItem",
    "TagCollection",
    "TagComplex",
    "TagsCategory",
    "TagsCategory",
    "TagsTrait",
    "TaskBaseCreate",
    "TaskChecklist",
    "TaskCollection",
    "TaskCreatePayload",
    "TaskDaily",
    "TaskHabit",
    "TaskKeepOption",
    "TaskKeepOption",
    "TaskReward",
    "TaskStatus",
    "TaskStatus",
    "TaskStatusType",
    "TaskTodo",
    "TaskType",
    "TaskType",
    "TodoCreate",
    "TodoStatus",
    "TodoStatus",
    "UserAchievements",
    "UserCollection",
    "UserCurrentState",
    "UserHistory",
    "UserMessage",
    "UserNotifications",
    "UserPreferences",
    "UserProfile",
    "UserStatsComputed",
    "UserStatsRaw",
    "UserTasksOrder",
    "UserTimestamps",
]
